### ISSUE TITLE
38463

### ISSUE THREAD

**Issue by gsongsong** [gsongsong/3gpp-message-formatter-ran3#9]
38463-f00
38463-f10
38463-f20

```
(node:12316) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'toUpperCase' of undefined
    at getExcelRowCol (C:\Users\s23.jeon\3gpp-message-formatter-ran3\node_modules\excel4node\distribution\lib\utils.js:127:21)
    at sortCellRefs (C:\Users\s23.jeon\3gpp-message-formatter-ran3\node_modules\excel4node\distribution\lib\utils.js:164:16)
    at Array.sort (native)
    at processRows (C:\Users\s23.jeon\3gpp-message-formatter-ran3\node_modules\excel4node\distribution\lib\worksheet\builder.js:141:34)
    at processNextRows (C:\Users\s23.jeon\3gpp-message-formatter-ran3\node_modules\excel4node\distribution\lib\worksheet\builder.js:175:13)
    at C:\Users\s23.jeon\3gpp-message-formatter-ran3\node_modules\excel4node\distribution\lib\worksheet\builder.js:178:9
    at new Promise (<anonymous>)
    at _addSheetData (C:\Users\s23.jeon\3gpp-message-formatter-ran3\node_modules\excel4node\distribution\lib\worksheet\builder.js:133:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at C:\Users\s23.jeon\3gpp-message-formatter-ran3\node_modules\excel4node\distribution\lib\worksheet\builder.js:494:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:12316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gsongsong** [comment]
7834fd2d883fa888e1496a28310c61a484d73a17 Buggy

**Comment by gsongsong** [comment]
6481926e45e7947eb567af80fa8d2f7fe49bbc9f
